# Copyright (c) 2021-2026, PostgreSQL Global Development Group

"""Tests for already-propagated WAL segments ending in incomplete WAL records."""

import shutil


# Build name of a WAL segment, used when filtering the contents of the server
# logs.
def wal_segment_name(tli, segment):
    return "%08X%08X%08X" % (tli, 0, segment)


# Calculate from a LSN (in bytes) its segment number and its offset, used
# when filtering the contents of the server logs.
def lsn_to_segment_and_offset(lsn, wal_segment_size):
    return (lsn // wal_segment_size, lsn % wal_segment_size)


# Get GUC value, converted to an int.
def get_int_setting(node, name):
    return int(
        node.safe_sql(
            f"SELECT setting FROM pg_settings WHERE name = '{name}'"))


# Find the start of a WAL page, based on an LSN in bytes.
def start_of_page(lsn, wal_block_size):
    return lsn & ~(wal_block_size - 1)


def test_043_no_contrecord_switch(create_pg):
    primary = create_pg(
        "primary", start=False, allows_streaming=True, has_archiving=True)

    # The configuration is chosen here to minimize the friction with
    # concurrent WAL activity.  checkpoint_timeout avoids noise with
    # checkpoint activity, and autovacuum is disabled to avoid any
    # WAL activity generated by it.
    primary.append_conf("""
autovacuum = off
checkpoint_timeout = '30min'
wal_keep_size = 1GB
""")

    primary.start()
    primary.backup("backup")

    primary.safe_sql("CREATE TABLE t AS SELECT 0")

    wal_segment_size = get_int_setting(primary, "wal_segment_size")
    wal_block_size = get_int_setting(primary, "wal_block_size")
    tli = int(primary.safe_sql(
        "SELECT timeline_id FROM pg_control_checkpoint()"))

    # Get close to the end of the current WAL page, enough to fit the
    # beginning of a record that spans on two pages, generating a
    # continuation record.
    primary.emit_wal(0)
    end_lsn = primary.advance_wal_out_of_record_splitting_zone(wal_block_size)

    # Do some math to find the record size that will overflow the page, and
    # write it.
    overflow_size = wal_block_size - (end_lsn % wal_block_size)
    end_lsn = primary.emit_wal(overflow_size)
    primary.stop("immediate")

    # Find the beginning of the page with the continuation record and fill
    # the entire page with zero bytes to simulate broken replication.
    start_page = start_of_page(end_lsn, wal_block_size)
    wal_file = primary.write_wal(tli, start_page, wal_segment_size, b"\x00" * wal_block_size)

    # Copy the file we just "hacked" to the archives.
    shutil.copy(wal_file, primary.archive_dir)

    # Start standby nodes and make sure they replay the file "hacked" from
    # the archives of the primary.
    standby1 = create_pg("standby1", start=False)
    standby1.init_from_backup(
        primary, "backup", standby=True, has_restoring=True)

    standby2 = create_pg("standby2", start=False)
    standby2.init_from_backup(
        primary, "backup", standby=True, has_restoring=True)

    log_size1 = standby1.log_position()
    log_size2 = standby2.log_position()

    standby1.start()
    standby2.start()

    segment, offset = lsn_to_segment_and_offset(start_page, wal_segment_size)
    segment_name = wal_segment_name(tli, segment)
    pattern = (
        rf"invalid magic number 0000 .* segment {segment_name}.* offset {offset}")

    # We expect both standby nodes to complain about an empty page when trying
    # to assemble the record that spans over two pages, so wait for such
    # reports in their logs.
    standby1.wait_for_log(pattern, log_size1)
    standby2.wait_for_log(pattern, log_size2)

    # Now check the case of a promotion with a timeline jump handled at
    # page boundary with a continuation record.
    standby1.promote()

    # This command forces standby2 to read a continuation record from the page
    # that is filled with zero bytes.
    standby1.safe_sql("SELECT pg_switch_wal()")

    # Make sure WAL moves forward.
    standby1.safe_sql(
        "INSERT INTO t SELECT * FROM generate_series(1, 1000)")

    # Configure standby2 to stream from just promoted standby1 (it also pulls
    # WAL files from the archive).  It should be able to catch up.
    standby2.enable_streaming(standby1)
    standby2.reload()
    standby1.wait_for_replay_catchup(standby2)

    result = standby2.safe_sql("SELECT count(*) FROM t")
    print(f"standby2: {result}")
    assert result == "1001", "check streamed content on standby2"
